chore(ci): Upgrade toolchain and add GHC 9.10.3 support
Remove mysql-haskell constraint-set as it is no longer needed.

diff --git a/.github/workflows/haskell-ci.yml b/.github/workflows/haskell-ci.yml
--- a/.github/workflows/haskell-ci.yml
+++ b/.github/workflows/haskell-ci.yml
@@ -8,14 +8,15 @@
 #
 # For more information, see https://github.com/haskell-CI/haskell-ci
 #
-# version: 0.19.20250315
+# version: 0.19.20260104
 #
-# REGENDATA ("0.19.20250315",["github","beam-mysql-haskell.cabal","--config","cabal.haskell-ci"])
+# REGENDATA ("0.19.20260104",["github","beam-mysql-haskell.cabal","--config","cabal.haskell-ci"])
 #
 name: Haskell-CI
 on:
   - push
   - pull_request
+  - merge_group
 jobs:
   linux:
     name: Haskell-CI - Linux - ${{ matrix.compiler }} ${{ matrix.database }}
@@ -28,9 +29,9 @@ jobs:
     strategy:
       matrix:
         include:
-          - compiler: ghc-9.8.4
+          - compiler: ghc-9.10.3
             compilerKind: ghc
-            compilerVersion: 9.8.4
+            compilerVersion: 9.10.3
             setup-method: ghcup
             allow-failure: false
             # Override default_authentication_plugin to mysql_native_password for MySQL 8.0.
@@ -39,6 +40,13 @@ jobs:
             # image repository: https://github.com/himura/docker-mysql-ci-tweak
             database: ghcr.io/himura/mysql-ci-tweak:8.0-tweak
             healthcheck: mysqladmin ping
+          - compiler: ghc-9.10.3
+            compilerKind: ghc
+            compilerVersion: 9.10.3
+            setup-method: ghcup
+            allow-failure: false
+            database: mariadb:11.7
+            healthcheck: healthcheck.sh --connect --innodb_initialized
           - compiler: ghc-9.8.4
             compilerKind: ghc
             compilerVersion: 9.8.4
@@ -73,12 +81,12 @@ jobs:
       - name: Install GHCup
         run: |
           mkdir -p "$HOME/.ghcup/bin"
-          curl -sL https://downloads.haskell.org/ghcup/0.1.40.0/x86_64-linux-ghcup-0.1.40.0 > "$HOME/.ghcup/bin/ghcup"
+          curl -sL https://downloads.haskell.org/ghcup/0.1.50.1/x86_64-linux-ghcup-0.1.50.1 > "$HOME/.ghcup/bin/ghcup"
           chmod a+x "$HOME/.ghcup/bin/ghcup"
       - name: Install cabal-install
         run: |
-          "$HOME/.ghcup/bin/ghcup" install cabal 3.12.1.0 || (cat "$HOME"/.ghcup/logs/*.* && false)
-          echo "CABAL=$HOME/.ghcup/bin/cabal-3.12.1.0 -vnormal+nowrap" >> "$GITHUB_ENV"
+          "$HOME/.ghcup/bin/ghcup" install cabal 3.16.0.0 || (cat "$HOME"/.ghcup/logs/*.* && false)
+          echo "CABAL=$HOME/.ghcup/bin/cabal-3.16.0.0 -vnormal+nowrap" >> "$GITHUB_ENV"
       - name: Install GHC (GHCup)
         if: matrix.setup-method == 'ghcup'
         run: |
@@ -154,7 +162,7 @@ jobs:
           chmod a+x $HOME/.cabal/bin/cabal-plan
           cabal-plan --version
       - name: checkout
-        uses: actions/checkout@v4
+        uses: actions/checkout@v5
         with:
           path: source
       - name: initial cabal.project for sdist
@@ -179,7 +187,7 @@ jobs:
           touch cabal.project.local
           echo "packages: ${PKGDIR_beam_mysql_haskell}" >> cabal.project
           echo "package beam-mysql-haskell" >> cabal.project
-          echo "    ghc-options: -Werror=missing-methods" >> cabal.project
+          echo "    ghc-options: -Werror=missing-methods -Werror=missing-fields" >> cabal.project
           cat >> cabal.project <<EOF
           EOF
           $HCPKG list --simple-output --names-only | perl -ne 'for (split /\s+/) { print "constraints: any.$_ installed\n" unless /^(beam-mysql-haskell)$/; }' >> cabal.project.local
@@ -195,28 +203,16 @@ jobs:
           key: ${{ runner.os }}-${{ matrix.compiler }}-${{ github.sha }}
           path: ~/.cabal/store
           restore-keys: ${{ runner.os }}-${{ matrix.compiler }}-
-      # DISABLE BY HANDS
-      # - name: install dependencies
-      #   run: |
-      #     $CABAL v2-build $ARG_COMPILER --disable-tests --disable-benchmarks --dependencies-only -j2 all
-      #     $CABAL v2-build $ARG_COMPILER $ARG_TESTS $ARG_BENCH --dependencies-only -j2 all
-      # - name: build
-      #   run: |
-      #     $CABAL v2-build $ARG_COMPILER $ARG_TESTS $ARG_BENCH all --write-ghc-environment-files=always
-      # - name: tests
-      #   run: |
-      #     $CABAL v2-test $ARG_COMPILER $ARG_TESTS $ARG_BENCH all --test-show-details=direct
-      - name: prepare for constraint sets
+      - name: install dependencies
         run: |
-          rm -f cabal.project.local
-      - name: constraint set mysql-haskell-1.1.6
+          $CABAL v2-build $ARG_COMPILER --disable-tests --disable-benchmarks --dependencies-only -j2 all
+          $CABAL v2-build $ARG_COMPILER $ARG_TESTS $ARG_BENCH --dependencies-only -j2 all
+      - name: build
         run: |
-          $CABAL v2-build $ARG_COMPILER --enable-tests --enable-benchmarks --constraint='tls <= 2.1.1' --constraint='data-default <= 0.7.1.3' --constraint='data-default-class <= 0.1.2.2' all --dry-run
-          cabal-plan topo | sort
-          $CABAL v2-build $ARG_COMPILER --enable-tests --enable-benchmarks --constraint='tls <= 2.1.1' --constraint='data-default <= 0.7.1.3' --constraint='data-default-class <= 0.1.2.2' --dependencies-only -j2 all
-          $CABAL v2-build $ARG_COMPILER --enable-tests --enable-benchmarks --constraint='tls <= 2.1.1' --constraint='data-default <= 0.7.1.3' --constraint='data-default-class <= 0.1.2.2' all
-          $CABAL v2-test $ARG_COMPILER --enable-tests --enable-benchmarks --constraint='tls <= 2.1.1' --constraint='data-default <= 0.7.1.3' --constraint='data-default-class <= 0.1.2.2' all
-          $CABAL v2-haddock --disable-documentation --haddock-all $ARG_COMPILER --with-haddock $HADDOCK --enable-tests --enable-benchmarks --constraint='tls <= 2.1.1' --constraint='data-default <= 0.7.1.3' --constraint='data-default-class <= 0.1.2.2' all
+          $CABAL v2-build $ARG_COMPILER $ARG_TESTS $ARG_BENCH all --write-ghc-environment-files=always
+      - name: tests
+        run: |
+          $CABAL v2-test $ARG_COMPILER $ARG_TESTS $ARG_BENCH all --test-show-details=direct
         env:
           MYSQL_HOST: mysql
           MYSQL_PORT: 3306
